### ISSUE TITLE
add more indicator options to chart

### ISSUE THREAD

**Issue by padamshrestha** [DaveSkender/Stock.Charts#163]
It would be great if you could share chart configuration for other indicators that you have been using in the documentation.

**Comment by DaveSkender** [comment]
My initial goal with this project was to just provide a few examples of the Stock Indicators for .NET library in action, and had no intention of creating a full charting solution.

With that said, I do already have some maturation and growth goals in [the Backlog](https://github.com/DaveSkender/Stock.Charts/projects/1) for the demo site that would extend the number of indicators.

I am seeking implementation help from the community if interested and able.

**Comment by DaveSkender** [comment]
@padamshrestha I'll be adding some more indicators to the chart soon.  I'll probably add these in small batches over time.  Are there any from the library of interest to you that I can prioritize?

**Comment by DaveSkender** [comment]
See #181 as an example of how to add an indicator.  If anyone is interested in contributing, this PR can be used as a template.  I'll eventually get around to adding them all, but help is appreciated.

**Comment by DaveSkender** [comment]
I’ve added more indicators, so I’m closing this issue, but please do recommend any others that you want me to prioritize.  I’ll slowly add them all, eventually.
