### ISSUE TITLE
stock chart for backtest

### ISSUE THREAD

**Issue by tiger2014** [DaveSkender/Stock.Charts#225]
I noticed that your website has a stock chart which can show the indicator on/below the chart.

Can you add it to the backtest project, so we can see the result directly on the chart?

Thanks!

**Comment by DaveSkender** [comment]
Oh that.  That is just a sample, not a _real_ backtest engine.  I’ll add a signals generator example to https://github.com/DaveSkender/Stock.Charts/issues/224
